apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: neoload-service
  namespace: keptn
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  runLatest:
    configuration:
      revisionTemplate:
        metadata:
          annotations:
            autoscaling.knative.dev/minScale: "1"
        spec:
          container:
            image: hrexed/keptn_neoload:latest
            env:
              - name: logging-level
                value: DEBUG
              - name: NL_WEB_HOST
                valueFrom:
                  secretKeyRef:
                    name: neoload
                    key: NL_WEB_HOST
              - name: NL_API_HOST
                valueFrom:
                  secretKeyRef:
                    name: neoload
                    key: NL_API_HOST
              - name: NL_API_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: neoload
                    key: NL_API_TOKEN
              - name: NL_WEB_ZONEID
                valueFrom:
                  secretKeyRef:
                    name: neoload
                    key: NL_WEB_ZONEID
              - name: NL_UPLOAD_HOST
                valueFrom:
                  secretKeyRef:
                    name: neoload
                    key: NL_UPLOAD_HOST
            imagePullPolicy: Always
            ports:
              - containerPort: 8080
            livenessProbe:
              httpGet:
                path: /health
              initialDelaySeconds: 60
              periodSeconds: 10
              timeoutSeconds: 15
            readinessProbe:
              httpGet:
                path: /health
              initialDelaySeconds: 60
              periodSeconds: 10
              timeoutSeconds: 15
---
apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: neoload-keptn-deployment-finished-subscription
  namespace: keptn
spec:
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: deployment-finished
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: neoload-service

